---
dist: xenial
language: ruby
cache: bundler
before_install:
  - gem update --system
  - gem update bundler
  - bundle --version
script:
  - 'bundle exec rake $CHECK'
matrix:
  fast_finish: true
  include:
  - rvm: 2.4.4
    bundler_args: --without system_tests development release
    env: PUPPET_VERSION="~> 5.0" CHECK=test
  - rvm: 2.5.3
    bundler_args: --without system_tests development release
    env: PUPPET_VERSION="~> 6.0" CHECK=test_with_coveralls
  - rvm: 2.5.3
    bundler_args: --without system_tests development release
    env: PUPPET_VERSION="~> 6.0" CHECK=rubocop
  - rvm: 2.4.4
    bundler_args: --without system_tests development release
    env: PUPPET_VERSION="~> 5.0" CHECK=build DEPLOY_TO_FORGE=yes
  - rvm: 2.5.3
    bundler_args: --without development release
    env: PUPPET_INSTALL_TYPE=agent BEAKER_IS_PE=no BEAKER_PUPPET_COLLECTION=puppet5 BEAKER_debug=true BEAKER_setfile=ubuntu1404-64 BEAKER_HYPERVISOR=docker CHECK=beaker
    services: docker
  - rvm: 2.5.3
    bundler_args: --without development release
    env: PUPPET_INSTALL_TYPE=agent BEAKER_IS_PE=no BEAKER_PUPPET_COLLECTION=puppet6 BEAKER_debug=true BEAKER_setfile=ubuntu1404-64 BEAKER_HYPERVISOR=docker CHECK=beaker
    services: docker
  - rvm: 2.5.3
    bundler_args: --without development release
    env: PUPPET_INSTALL_TYPE=agent BEAKER_IS_PE=no BEAKER_PUPPET_COLLECTION=puppet5 BEAKER_debug=true BEAKER_setfile=ubuntu1604-64 BEAKER_HYPERVISOR=docker CHECK=beaker
    services: docker
  - rvm: 2.5.3
    bundler_args: --without development release
    env: PUPPET_INSTALL_TYPE=agent BEAKER_IS_PE=no BEAKER_PUPPET_COLLECTION=puppet6 BEAKER_debug=true BEAKER_setfile=ubuntu1604-64 BEAKER_HYPERVISOR=docker CHECK=beaker
    services: docker
  - rvm: 2.5.3
    bundler_args: --without development release
    env: PUPPET_INSTALL_TYPE=agent BEAKER_IS_PE=no BEAKER_PUPPET_COLLECTION=puppet5 BEAKER_debug=true BEAKER_setfile=ubuntu1804-64 BEAKER_HYPERVISOR=docker CHECK=beaker
    services: docker
  - rvm: 2.5.3
    bundler_args: --without development release
    env: PUPPET_INSTALL_TYPE=agent BEAKER_IS_PE=no BEAKER_PUPPET_COLLECTION=puppet6 BEAKER_debug=true BEAKER_setfile=ubuntu1804-64 BEAKER_HYPERVISOR=docker CHECK=beaker
    services: docker
  - rvm: 2.5.3
    bundler_args: --without development release
    env: PUPPET_INSTALL_TYPE=agent BEAKER_IS_PE=no BEAKER_PUPPET_COLLECTION=puppet5 BEAKER_debug=true BEAKER_setfile=centos6-64 BEAKER_HYPERVISOR=docker CHECK=beaker
    services: docker
  - rvm: 2.5.3
    bundler_args: --without development release
    env: PUPPET_INSTALL_TYPE=agent BEAKER_IS_PE=no BEAKER_PUPPET_COLLECTION=puppet6 BEAKER_debug=true BEAKER_setfile=centos6-64 BEAKER_HYPERVISOR=docker CHECK=beaker
    services: docker
  - rvm: 2.5.3
    bundler_args: --without development release
    env: PUPPET_INSTALL_TYPE=agent BEAKER_IS_PE=no BEAKER_PUPPET_COLLECTION=puppet5 BEAKER_debug=true BEAKER_setfile=centos7-64 BEAKER_HYPERVISOR=docker CHECK=beaker
    services: docker
  - rvm: 2.5.3
    bundler_args: --without development release
    env: PUPPET_INSTALL_TYPE=agent BEAKER_IS_PE=no BEAKER_PUPPET_COLLECTION=puppet6 BEAKER_debug=true BEAKER_setfile=centos7-64 BEAKER_HYPERVISOR=docker CHECK=beaker
    services: docker
  - rvm: 2.5.3
    bundler_args: --without development release
    env: PUPPET_INSTALL_TYPE=agent BEAKER_IS_PE=no BEAKER_PUPPET_COLLECTION=puppet5 BEAKER_debug=true BEAKER_setfile=debian8-64 BEAKER_HYPERVISOR=docker CHECK=beaker
    services: docker
  - rvm: 2.5.3
    bundler_args: --without development release
    env: PUPPET_INSTALL_TYPE=agent BEAKER_IS_PE=no BEAKER_PUPPET_COLLECTION=puppet6 BEAKER_debug=true BEAKER_setfile=debian8-64 BEAKER_HYPERVISOR=docker CHECK=beaker
    services: docker
  - rvm: 2.5.3
    bundler_args: --without development release
    env: PUPPET_INSTALL_TYPE=agent BEAKER_IS_PE=no BEAKER_PUPPET_COLLECTION=puppet5 BEAKER_debug=true BEAKER_setfile=debian9-64 BEAKER_HYPERVISOR=docker CHECK=beaker
    services: docker
  - rvm: 2.5.3
    bundler_args: --without development release
    env: PUPPET_INSTALL_TYPE=agent BEAKER_IS_PE=no BEAKER_PUPPET_COLLECTION=puppet6 BEAKER_debug=true BEAKER_setfile=debian9-64 BEAKER_HYPERVISOR=docker CHECK=beaker
    services: docker
  - rvm: 2.5.3
    bundler_args: --without development release
    env: PUPPET_INSTALL_TYPE=agent BEAKER_IS_PE=no BEAKER_PUPPET_COLLECTION=puppet5 BEAKER_debug=true BEAKER_setfile=debian10-64 BEAKER_HYPERVISOR=docker CHECK=beaker
    services: docker
  - rvm: 2.5.3
    bundler_args: --without development release
    env: PUPPET_INSTALL_TYPE=agent BEAKER_IS_PE=no BEAKER_PUPPET_COLLECTION=puppet6 BEAKER_debug=true BEAKER_setfile=debian10-64 BEAKER_HYPERVISOR=docker CHECK=beaker
    services: docker
branches:
  only:
  - master
  - /^v\d/
notifications:
  email: false
  irc:
    on_success: always
    on_failure: always
    channels:
      - "chat.freenode.org#voxpupuli-notifications"
deploy:
  provider: puppetforge
  user: puppet
  password:
    secure: "LlUcdbmw7l791vD0samUkh2cuyUF49JTjlb9jIoVUYH7ZIJywSl5hZGVLmUhr4aKhPIWhLG1psAeRtjzi3xtgxP+C78RtjIZ1TE/Jglloe0heKz8E3yUfXbl/GX1B5uQhIoIZaqPZd2OuINSC4P9NvsTfai3i85JNXYs5w5QTaLToS6fU+Gb9iut8KCSPeFdA7EEDDcNJUyMVUTuc5w7/rIcPIy7AXXDDkJNdPM8m70b8Skm18afkZZ1LmwpNnsf+l1vQqtId2QyetyFOW566chSgEbswfWFxJL7g37d4l5rVBwkV/vN8iNc5NIc6oih2IqpX8fcEmx1lQ4P8mfvIm32FJ9pI1Utg80vlhzzOFrENyHyTbQ6d0fNdGo85q2ZBdXVuv+/Bq4xsXHkqke/JXMzDtGpCfLKBaY97Jlo56T313DY8NQTbO3svaazJn2EZTC0qIZ0TBBdr3qAbuF5myanxlhBcH/cpMr6rJ/7KS4XNcQPbzvompWeNoFgn0Lp49/HfX2hhGKOyRplCpO7zXzwe1WvVOh3mk5fPmHrYYffzXME0Mx0REuJGCxavsAIf26PS0+/8EMGTHemkeuRj1ISwBHkBdiiJtjIv40gcwoiTqxZsUa+aNqFb6ACN8c3jJa7slbBemUFODVc8zklYw6Dd+ojIAzIaH/eY4co3IY="
  on:
    tags: true
    # all_branches is required to use tags
    all_branches: true
    # Only publish the build marked with "DEPLOY_TO_FORGE"
    condition: "$DEPLOY_TO_FORGE = yes"
